INSERT INTO EMP_RECEIVE_POINTS_TALLY (ID,EMP_USERNAME,YEAR,POINTS_TO_REDEEM) VALUES (receivepoints_seq.nextval,'ABHILASHAK','2018',0);
INSERT INTO EMP_RECEIVE_POINTS_TALLY (ID,EMP_USERNAME,YEAR,POINTS_TO_REDEEM) VALUES (receivepoints_seq.nextval,'PRABHAT','2018',0);
INSERT INTO EMP_RECEIVE_POINTS_TALLY (ID,EMP_USERNAME,YEAR,POINTS_TO_REDEEM) VALUES (receivepoints_seq.nextval,'BANERJEE','2018',0);
INSERT INTO EMP_RECEIVE_POINTS_TALLY (ID,EMP_USERNAME,YEAR,POINTS_TO_REDEEM) VALUES (receivepoints_seq.nextval,'ADITIC','2018',0);
INSERT INTO EMP_RECEIVE_POINTS_TALLY (ID,EMP_USERNAME,YEAR,POINTS_TO_REDEEM) VALUES (receivepoints_seq.nextval,'MEGHAK','2018',0);
INSERT INTO EMP_RECEIVE_POINTS_TALLY (ID,EMP_USERNAME,YEAR,POINTS_TO_REDEEM) VALUES (receivepoints_seq.nextval,'ASHAYJ','2018',0);
-- similar for emp_give_points with initial starting points as 1500


INSERT INTO EMP_GIVE_POINTS_TALLY (ID,EMP_USERNAME,MONTH,YEAR,POINTS_TO_GIVE) VALUES (givepoints_seq.nextval,'ABHILASHAK',to_char(CURRENT_TIMESTAMP , 'MONTH'),'2018',1000);
INSERT INTO EMP_GIVE_POINTS_TALLY (ID,EMP_USERNAME,MONTH,YEAR,POINTS_TO_GIVE) VALUES (givepoints_seq.nextval,'PRABHAT',to_char(CURRENT_TIMESTAMP , 'MONTH'),'2018',1000);
INSERT INTO EMP_GIVE_POINTS_TALLY (ID,EMP_USERNAME,MONTH,YEAR,POINTS_TO_GIVE) VALUES (givepoints_seq.nextval,'BANERJEE',to_char(CURRENT_TIMESTAMP , 'MONTH'),'2018',1000);
INSERT INTO EMP_GIVE_POINTS_TALLY (ID,EMP_USERNAME,MONTH,YEAR,POINTS_TO_GIVE) VALUES (givepoints_seq.nextval,'ADITIC',to_char(CURRENT_TIMESTAMP , 'MONTH'),'2018',1000);
INSERT INTO EMP_GIVE_POINTS_TALLY (ID,EMP_USERNAME,MONTH,YEAR,POINTS_TO_GIVE) VALUES (givepoints_seq.nextval,'MEGHAK',to_char(CURRENT_TIMESTAMP , 'MONTH'),'2018',1000);
INSERT INTO EMP_GIVE_POINTS_TALLY (ID,EMP_USERNAME,MONTH,YEAR,POINTS_TO_GIVE) VALUES (givepoints_seq.nextval,'ASHAYJ',to_char(CURRENT_TIMESTAMP , 'MONTH'),'2018',1000);
-- similar for emp_give_points with initial starting points as 1500


DELETE FROM
  EMP_GIVE_POINTS_TALLY WHERE MONTH='NOVEMBER';
  
  commit;
  
  SELECT EMP_USERNAME,1000
  FROM (SELECT DISTINCT EMP_USERNAME FROM EMP_GIVE_POINTS_TALLY);
  
  SELECT * FROm EMP_GIVE_POINTS_TALLY;
  
