create or replace TRIGGER TRG_BEFORE_POINTS_INSERT
BEFORE INSERT ON POINTS_TRANSACTION
FOR EACH ROW

BEGIN
 IF :new.BY_EMP = :NEW.TO_EMP
 THEN RAISE_APPLICATION_ERROR(-20000,'FROM AND TO EMPLOYEE CANNOT BE SAME');
 END IF;
END;